In [1]:
import numpy as np

In [2]:
import pandas as pd

Creating a DataFrame

In [6]:
data={
    "name":["akshita","anjali","himanshu"],
    "age":[19,22,21],
    "subject":["Maths","English","Arts"]
}
df=pd.DataFrame(data)

In [7]:
df

       name  age  subject
0   akshita   19    Maths
1    anjali   22  English
2  himanshu   21     Arts

In [9]:
data=[
    ["Akshita" ,19,200000],
    ["shreyansh",20,200000],
    ["Ranbir",25,300000]
]
df=pd.DataFrame(data)
df
col=["Name","Age","Salary"]
df=pd.DataFrame(data,columns=col)
df

        Name  Age  Salary
0    Akshita   19  200000
1  shreyansh   20  200000
2     Ranbir   25  300000

Selection and Indexing of Columns

In [17]:
df[["Name","Age"]]

        Name  Age
0    Akshita   19
1  shreyansh   20
2     Ranbir   25

In [18]:
df["designation"]=["Engineer","Writer","Painter"]

In [19]:
df

        Name  Age  Salary designation
0    Akshita   19  200000    Engineer
1  shreyansh   20  200000      Writer
2     Ranbir   25  300000     Painter

In [20]:
df.drop("designation",axis=1)

        Name  Age  Salary
0    Akshita   19  200000
1  shreyansh   20  200000
2     Ranbir   25  300000

In [21]:
df

        Name  Age  Salary designation
0    Akshita   19  200000    Engineer
1  shreyansh   20  200000      Writer
2     Ranbir   25  300000     Painter

In [22]:
df.drop(["designation"],axis=1,inplace=True)

In [23]:
df

        Name  Age  Salary
0    Akshita   19  200000
1  shreyansh   20  200000
2     Ranbir   25  300000

Selecting rows

In [25]:
df.loc[0]

Name      Akshita
Age            19
Salary     200000
Name: 0, dtype: object

Index location (iloc)

In [26]:
df.iloc[2]

Name      Ranbir
Age           25
Salary    300000
Name: 2, dtype: object

Conditional selection

In [29]:
# i want to see person below the age of 20 or equal to 20 
df[df["Age"]<=20]

        Name  Age  Salary
0    Akshita   19  200000
1  shreyansh   20  200000

In [31]:
# i want to se person below 20 and called akshita 
df[(df["Name"]=="Akshita") & (df["Age"]<=20)]

      Name  Age  Salary
0  Akshita   19  200000