In [2]:
import numpy as np
import pandas as pd

Merging two dataframes

In [8]:
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace"],
    "Course": ["CSE", "IT", "ECE", "ME", "CSE", "IT", "ECE"],
    "Age": [20, 21, 22, 23, 20, 21, 22]
}
df_students = pd.DataFrame(students)
df_students

   Student_ID     Name Course  Age
0         101    Alice    CSE   20
1         102      Bob     IT   21
2         103  Charlie    ECE   22
3         104    David     ME   23
4         105      Eva    CSE   20
5         106    Frank     IT   21
6         107    Grace    ECE   22

In [9]:
marks = {
    "Student_ID": [101, 102, 103, 105, 106, 107, 108],
    "Maths": [88, 76, 91, 82, 79, 95, 70],
    "Science": [90, 72, 94, 85, 80, 98, 68],
    "English": [85, 70, 92, 88, 76, 96, 74]
}
df_marks = pd.DataFrame(marks)
df_marks

   Student_ID  Maths  Science  English
0         101     88       90       85
1         102     76       72       70
2         103     91       94       92
3         105     82       85       88
4         106     79       80       76
5         107     95       98       96
6         108     70       68       74

In [ ]:
pd.merge(df_students,df_marks,on="Student_ID",how="inner")

   Student_ID     Name Course  Age  Maths  Science  English
0         101    Alice    CSE   20     88       90       85
1         102      Bob     IT   21     76       72       70
2         103  Charlie    ECE   22     91       94       92
3         105      Eva    CSE   20     82       85       88
4         106    Frank     IT   21     79       80       76
5         107    Grace    ECE   22     95       98       96

In [13]:
pd.merge(df_students,df_marks,on="Student_ID",how="outer") #merges on the basis of column

   Student_ID     Name Course   Age  Maths  Science  English
0         101    Alice    CSE  20.0   88.0     90.0     85.0
1         102      Bob     IT  21.0   76.0     72.0     70.0
2         103  Charlie    ECE  22.0   91.0     94.0     92.0
3         104    David     ME  23.0    NaN      NaN      NaN
4         105      Eva    CSE  20.0   82.0     85.0     88.0
5         106    Frank     IT  21.0   79.0     80.0     76.0
6         107    Grace    ECE  22.0   95.0     98.0     96.0
7         108      NaN    NaN   NaN   70.0     68.0     74.0

In [ ]:
pd.merge(df_students,df_marks,on="Student_ID",how="left") #merging on the basis of left table

   Student_ID     Name Course  Age  Maths  Science  English
0         101    Alice    CSE   20   88.0     90.0     85.0
1         102      Bob     IT   21   76.0     72.0     70.0
2         103  Charlie    ECE   22   91.0     94.0     92.0
3         104    David     ME   23    NaN      NaN      NaN
4         105      Eva    CSE   20   82.0     85.0     88.0
5         106    Frank     IT   21   79.0     80.0     76.0
6         107    Grace    ECE   22   95.0     98.0     96.0

In [15]:
pd.merge(df_students,df_marks,on="Student_ID",how="right")

   Student_ID     Name Course   Age  Maths  Science  English
0         101    Alice    CSE  20.0     88       90       85
1         102      Bob     IT  21.0     76       72       70
2         103  Charlie    ECE  22.0     91       94       92
3         105      Eva    CSE  20.0     82       85       88
4         106    Frank     IT  21.0     79       80       76
5         107    Grace    ECE  22.0     95       98       96
6         108      NaN    NaN   NaN     70       68       74

Concatenation of two dataframes

In [16]:
cse_students = {
    "Student_ID": [101, 102, 103],
    "Name": ["Alice", "Bob", "Charlie"],
    "Course": ["CSE", "CSE", "CSE"],
    "Marks": [88, 76, 91]
}

df_cse = pd.DataFrame(cse_students)

In [17]:
df_cse

   Student_ID     Name Course  Marks
0         101    Alice    CSE     88
1         102      Bob    CSE     76
2         103  Charlie    CSE     91

In [ ]:
it_students = {
    "Student_ID": [104, 105, 106],
    "Name": ["David", "Eva", "Frank"],
    "Course": ["IT", "IT", "IT"],
    "Marks": [65, 82, 79]
}

df_it = pd.DataFrame(it_students)

In [19]:
df_it

   Student_ID   Name Course  Marks
0         104  David     IT     65
1         105    Eva     IT     82
2         106  Frank     IT     79

In [23]:
pd.concat([df_it,df_cse]) #this will concatenate based on columns

   Student_ID     Name Course  Marks
0         104    David     IT     65
1         105      Eva     IT     82
2         106    Frank     IT     79
0         101    Alice    CSE     88
1         102      Bob    CSE     76
2         103  Charlie    CSE     91

In [ ]:
pd.concat([df_it,df_cse],axis=1) #it will concate rows wise

   Student_ID   Name Course  Marks  Student_ID     Name Course  Marks
0         104  David     IT     65         101    Alice    CSE     88
1         105    Eva     IT     82         102      Bob    CSE     76
2         106  Frank     IT     79         103  Charlie    CSE     91

Joining of dataframes

In [37]:
import pandas as pd

students = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Course": ["CSE", "IT", "ECE", "ME", "CSE"]
}

df_students = pd.DataFrame(students).set_index("Student_ID")

In [30]:
df_students

   Student_ID     Name Course
0         101    Alice    CSE
1         102      Bob     IT
2         103  Charlie    ECE
3         104    David     ME
4         105      Eva    CSE

In [ ]:
marks = {
    "Student_ID": [101, 102, 103, 105, 106],
    "Maths": [88, 76, 91, 82, 70],
    "Science": [90, 72, 94, 85, 68]
}

df_marks = pd.DataFrame(marks).set_index("Student_ID")

In [34]:
df_marks

   Student_ID  Maths  Science
0         101     88       90
1         102     76       72
2         103     91       94
3         105     82       85
4         106     70       68

In [38]:
df_students.join(df_marks)

               Name Course  Student_ID  Maths  Science
Student_ID
101           Alice    CSE         NaN    NaN      NaN
102             Bob     IT         NaN    NaN      NaN
103         Charlie    ECE         NaN    NaN      NaN
104           David     ME         NaN    NaN      NaN
105             Eva    CSE         NaN    NaN      NaN