In [1]:
import numpy as np
import pandas as pd

In [7]:
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "Age": [20, 21, np.nan, 22, 20, 23, 21, np.nan, 22, 20],
    "Gender": ["Female", "Male", "Male", "Male", "Female", "Male", "Female", "Male", "Female", "Male"],
    "Math": [85, 78, 92, 65, 88, np.nan, 95, 70, 90, 82],
    "Science": [90, np.nan, 94, 70, 91, 75, 98, 68, np.nan, 85],
    "English": [88, 81, 90, np.nan, 89, 72, 96, 71, 93, np.nan],
    "Attendance": [95, 89, 97, 85, np.nan, 80, 99, 75, 92, 88],
    "City": ["Delhi", "Mumbai", "Bangalore", np.nan, "Pune", "Delhi", "Mumbai", "Bangalore", np.nan, "Chennai"]
}

In [9]:
df = pd.DataFrame(data)

find null value

In [13]:
df.isna()

,Student_ID,Name,Age,Gender,Math,Science,English,Attendance,City
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False
2,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,False,True,False
5,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,True,False,False,False,False,False,False
8,False,False,False,False,False,True,False,False,True
9,False,False,False,False,False,False,True,False,False

In [14]:
df.isna().sum()

Student_ID    0
Name          0
Age           2
Gender        0
Math          1
Science       2
English       2
Attendance    1
City          2
dtype: int64

Removing missing values (Cleaning the data )

In [18]:
#it works based on rows 
df.dropna() #it removes all the rows that contains null  but just a snapshot

   Student_ID   Name   Age  Gender  Math  Science  English  Attendance    City
0         101  Alice  20.0  Female  85.0     90.0     88.0        95.0   Delhi
6         107  Grace  21.0  Female  95.0     98.0     96.0        99.0  Mumbai

In [24]:
#using threash ( it will give only those row that will have a particular non null columns )
df.dropna(thresh=8)

,Student_ID,Name,Age,Gender,Math,Science,English,Attendance,City
0,101,Alice,20.0,Female,85.0,90.0,88.0,95.0,Delhi
1,102,Bob,21.0,Male,78.0,NaN,81.0,89.0,Mumbai
2,103,Charlie,NaN,Male,92.0,94.0,90.0,97.0,Bangalore
4,105,Eva,20.0,Female,88.0,91.0,89.0,NaN,Pune
5,106,Frank,23.0,Male,NaN,75.0,72.0,80.0,Delhi
6,107,Grace,21.0,Female,95.0,98.0,96.0,99.0,Mumbai
7,108,Henry,NaN,Male,70.0,68.0,71.0,75.0,Bangalore
9,110,Jack,20.0,Male,82.0,85.0,NaN,88.0,Chennai

Filling the missing value

In [25]:
df.fillna(2)

,Student_ID,Name,Age,Gender,Math,Science,English,Attendance,City
0,101,Alice,20.0,Female,85.0,90.0,88.0,95.0,Delhi
1,102,Bob,21.0,Male,78.0,2.0,81.0,89.0,Mumbai
2,103,Charlie,2.0,Male,92.0,94.0,90.0,97.0,Bangalore
3,104,David,22.0,Male,65.0,70.0,2.0,85.0,2
4,105,Eva,20.0,Female,88.0,91.0,89.0,2.0,Pune
5,106,Frank,23.0,Male,2.0,75.0,72.0,80.0,Delhi
6,107,Grace,21.0,Female,95.0,98.0,96.0,99.0,Mumbai
7,108,Henry,2.0,Male,70.0,68.0,71.0,75.0,Bangalore
8,109,Ivy,22.0,Female,90.0,2.0,93.0,92.0,2
9,110,Jack,20.0,Male,82.0,85.0,2.0,88.0,Chennai